version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000" # Portainer HTTP access
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Docker socket
      - "portainer_data:/data" # Portainer data
    depends_on:
      - portainer_agent

  portainer_agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Docker socket
      - "/var/lib/docker/volumes:/var/lib/docker/volumes" # Docker volumes

volumes:
  portainer_data:
